type TCrawlerTapsiFood = {
  status: boolean;
  message: string;
  data: {
    vendor: {
      vendorCode: string;
      vendorStatus: string;
      vendorHasInServiceState: boolean;
      title: string;
      minimumBasket: number;
      packingPrice: number;
      tax: boolean;
      deliveryTypes: [
        {
          deliveryType: string;
          deliveryPrice: number;
        },
      ];
      shiftWork: string;
      badges: string[];
      discount: number;
      mainImage: string;
      logo: string;
      businessTypeId: number;
      cityId: number;
      latitude: number;
      longitude: number;
      eta: number;
    };
    review: { rateCount: number; commentCount: number; rate: number };
    categories: {
      categoryId: string;
      categoryName: string;
      products: {
        productId: string;
        productName: string;
        productDescription: string;
        images: string[];
        productVariations: {
          productVariationId: string;
          productVariationName: string;
          productVariationDescription: string | null;
          price: number;
          discountRatio: number;
          priceAfterDiscount: number;
          stock: number;
          capacity: number;
          vendorDiscountRatio: number | null;
          tapsiFoodDiscountRatio: number | null;
          discountStock: number | null;
          mandatoryOptionCategoryIds: [];
          optionCategories: [];
        }[];
      }[];
    }[];
  };
};

type TCrawlerSnapFood = {
  status: boolean;
  data: {
    vendor: {
      id: number;
      rejectOutOfZone: boolean;
      brokerType: null;
      state: string;
      preOrderOnly: boolean;
      noOrder: boolean;
      city_id: string;
      city: string;
      area: string;
      createdAt: {
        date: string;
        timezone_type: number;
        timezone: string;
      };
      inPlaceDelivery: boolean;
      expeditionType: string;
      pickup: boolean;
      title: string;
      chainCode: null;
      chainTitle: null;
      chainId: null;
      branchTitle: null;
      englishTitle: string;
      commentCount: number;
      textCommentCount: number;
      customerPhone: string;
      rating: number;
      logo: string;
      taxEnabled: boolean;
      taxIncluded: boolean;
      taxEnabledInProducts: boolean;
      taxEnabledInPackaging: boolean;
      taxEnabledInDeliveryFee: boolean;
      taxVisible: boolean;
      vatVisible: boolean;
      tax: number;
      serviceFee: number;
      deliveryArea: string;
      delay: string;
      minOrder: number;
      address: string;
      website: null;
      stockEnabled: boolean;
      lat: number;
      lon: number;
      onlineDeliveryEnabled: boolean;
      recommendedFor: null;
      establishment: string;
      mostPopularItems: null;
      costsForTwo: null;
      containerPriceType: string;
      containerFee: number;
      deliveryType: string;
      deliveryDescription: string;
      preOrderStatus: string;
      coverName: null;
      coverPath: string;
      isVegetarian: boolean;
      deliveryGuarantee: boolean;
      fidilioEnabled: boolean;
      fidilioLink: null;
      expressShift: null;
      vendorStatus: boolean;
      vendorType: string;
      vendorSubType: number;
      superTypeAlias: string;
      expressDeliveryTime: number;
      feeRange: null;
      commissionRule: string;
      commissionType: string;
      commissionEnabledForPackaging: boolean;
      commissionEnabledForDeliveryFee: boolean;
      vendorTypeTitle: string;
      budgetClass: string;
      productTypeTitle: string;
      maxDeliveryRadius: number;
      isEcommerce: boolean;
      satisfactionGuarantee: boolean;
      newType: string;
      newTypeTitle: string;
      vendorCode: string;
      shareLink: string;
      phone: string;
      isOpen: boolean;
      isOpenNow: boolean;
      reopeningTime: {
        date: string;
        timezone_type: number;
        timezone: string;
      };
      schedules: {
        weekday: number;
        allDay: boolean;
        startHour: string;
        stopHour: string;
      }[];
      preorderToday: {
        weekday: string;
        name: string;
        intervals: { label: string; value: string }[];
      };
      preorderTomorrow: {
        weekday: string;
        name: string;
        intervals: { label: string; value: string }[];
      };
      preorderAfterTomorrow: null;
      badges: [];
      discountType: null;
      discountValue: number;
      discountVendorShareValue: number;
      discountForAll: boolean;
      allowedPaymentTypes: [];
      isCommissionForDiscount: boolean;
      discountStartHour1: string;
      discountStopHour1: string;
      discountStartHour2: string;
      discountStopHour2: string;
      discountValueForView: number;
      reviewStars: {
        one: number;
        two: number;
        three: number;
        four: number;
        five: number;
      };
      topProducts: [];
      has_coupon: boolean;
      has_packaging: boolean;
      childType: string;
      tagNames: null;
      isPro: boolean;
      isEconomical: boolean;
      paymentTypes: number[];
      paymentTypeCodes: 'ONLINE' | 'CREDIT'[];
      paymentTypesToShow: 'آنلاین'[];
      isFavorite: boolean;
      discount: number;
      ZFDeliveryFeeDiscount: number;
      vendorMapState: number;
      vendorStateTitle: string;
      vendorState: number;
      vendorStateText: null;
      deliveryFee: number;
      totalDeliveryTime: null;
      maxDeliveryTime: null;
      minDeliveryTime: null;
      delivery: null;
      isZFExpress: boolean;
    };
    stocks: [];
    menus: {
      categoryId: number;
      category: string;
      description: null;
      image: null;
      products: {
        id: number;
        stock: null;
        capacity: number;
        productVariationTitle: string;
        title: string;
        description: string;
        price: number;
        type: [];
        discount: number;
        discountRatio: number;
        productToppings: [];
        productTitle: null;
        createdAt: {
          date: string;
          timezone_type: number;
          timezone: string;
        };
        productId: null;
        containerPrice: number;
        vat: number;
        images: {
          imageId: number;
          imageSrc: string;
          imageThumbnailSrc: string;
          imageUserType: string;
          imageUsername: null;
          imageDescription: null;
          imagePosition: null;
        }[];
        categoryId: number;
        categoryTile: string;
        rating: number;
        disabledUntil: boolean;
        likesCount: number;
        disLikesCount: number;
        popularityBadgeName: string;
        popularityBadgeURL: string;
        popularityScore: number;
        videoLink: null | string | string[];
      }[];
    }[];
    sort: [];
  };
};
